// <auto-generated />
using Emma.Blog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace Emma.Blog.Data.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20180110134504_AddTableComment")]
    partial class AddTableComment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Emma.Blog.Data.Models.Comment", b =>
                {
                    b.Property<long>("CommentId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("UserId");

                    b.Property<string>("Name");

                    b.Property<string>("Content");

                    b.Property<int>("DeleteFlag");

                    b.Property<DateTime>("CreateTime");

                    b.HasKey("CommentId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Emma.Blog.Data.Models.Post", b =>
                {
                    b.Property<long>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ReadNumber");

                    b.Property<string>("Tag");

                    b.Property<string>("Title");

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreateTime");

                    b.Property<long>("UserId");

                    b.HasKey("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Emma.Blog.Data.Models.User", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("HeadImg");

                    b.Property<string>("NickName");

                    b.Property<string>("Password")
                        .HasMaxLength(100);

                    b.Property<string>("Phone");

                    b.Property<string>("UserName")
                        .HasMaxLength(100);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Emma.Blog.Data.Models.Post", b =>
                {
                    b.HasOne("Emma.Blog.Data.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
